### ISSUE TITLE
No process-doc for markdown syntax

### ISSUE THREAD

**Issue by vindarel** [mmontone/erudite#2]
Hi,

I'm interested to write embedded doc in markdown (as advertised :D ) but it seems support doesn't exist.

```
(erudite:erudite t "test.lisp" :output-type :markdown :syntax :markdown)
ERROR: There is no primary method for the generic function
         #<STANDARD-GENERIC-FUNCTION ERUDITE::PROCESS-DOC (5)>
       when called with arguments
         (:MARKDOWN :MARKDOWN "Hello erudite."
          #<SB-IMPL::STRING-OUTPUT-STREAM {10049C0123}>
          #<CLOSURE (FLET ERUDITE::PROCESS-CONT :IN ERUDITE::PROCESS-FRAGMENT) {10049C673B}>).
See also:
```

And indeed, there is no `process-doc` method that specializes on :markdown.

I see a `syntax/markdown.lisp` file, then no `*markdown-syntax*` as with `*erudite-syntax*`. Is it ready, is there much left ?

Regards

**Comment by mmontone** [comment]
What happens if you try:
```
(defmethod process-doc ((syntax (eql :markdown)) output-type line stream cont)
  (write-string line stream)
  (terpri stream)
  (funcall cont))
```

**Comment by vindarel** [comment]
It runs.

It doesn't process the syntax, but writing in markdown and outputting to markdown seems to work just fine.

```
;; a markdown [link](https://www.gnu.org/software/emacs/)

;; # First section

(defun hello ())
```


    (erudite:erudite t "foo.lisp" :output-type :markdown :syntax :markdown)

outputs

```
a markdown [link](https://www.gnu.org/software/emacs/)
# First section

```lisp

(defun hello ())
\```  # escape for github
```

**Comment by mmontone** [comment]
Aha. I think that's just what is being done for other syntax too. I think I add that method then.

**Comment by mmontone** [comment]
I've added the method specialization.
