### ISSUE TITLE
How to comment code ? 

### ISSUE THREAD

**Issue by vindarel** [mmontone/erudite#4]
I have unfinished code that I'd like to show in the documentation, but that shouldn't be run. If I comment it inside `#|…|#`, it is outputted as regular text (expected). If I comment it with `;;`, it is a it annoying.
 So I thought there could be a `@comment` syntax, is there one  ? (couldn't see one in erudite.lisp) I also could use markdown's code snippet inside the `#|`, but markdown syntax for input is not supported.

thanks

**Comment by vindarel** [comment]
erratum: code commented in `;;` is ignored: makes sense!

**Comment by vindarel** [comment]
The workaround for the moment is simply to put this code in another lisp file, not loaded by the program.

**Comment by mmontone** [comment]
I think I didn't implement that, but should have.

**Comment by vindarel** [comment]
I found the `@verbatim` tag. It's in the syntax and not in the example (erudite.lisp).

Let's close this by enhancing the doc.

**Comment by vindarel** [comment]
I also found Serapeum's `comment` macro: https://github.com/ruricolist/serapeum/blob/master/REFERENCE.md#comment-body-body

**Comment by mmontone** [comment]
The doc was enhanced.
